//! Assembly syntax highlighting via arborium.
//!
//! `Highlighter` is not `Send`/`Sync` so we keep one per task; constructing
//! it is cheap (the grammar is statically linked through the
//! `arborium-asm` crate).

use arborium::Highlighter;

pub struct AsmHighlighter {
    inner: Highlighter,
}

impl AsmHighlighter {
    pub fn new() -> Self {
        // Use the default `CustomElements` HTML format: `<a-k>...</a-k>`,
        // `<a-f>...</a-f>`, etc. Theme CSS generated by `cargo xtask
        // codegen` (which runs `Theme::to_css`) targets these tags.
        Self {
            inner: Highlighter::new(),
        }
    }

    /// Highlight one line of assembly. Returns class-name HTML on success;
    /// falls back to plain (escaped) text on error so the UI still renders.
    pub fn highlight_line(&mut self, asm: &str) -> String {
        match self.inner.highlight("asm", asm) {
            Ok(html) => html,
            Err(err) => {
                tracing::warn!("arborium failed on {asm:?}: {err}");
                html_escape(asm)
            }
        }
    }
}

impl Default for AsmHighlighter {
    fn default() -> Self {
        Self::new()
    }
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn highlights_simple_mov() {
        let mut hl = AsmHighlighter::new();
        let html = hl.highlight_line("mov rax, 0x42");
        // Default format is custom elements: `<a-f>`, `<a-v>`, etc. Just
        // sanity-check the output isn't empty and contains *some* tag.
        assert!(html.contains("<a-"), "expected custom-tag output, got {html:?}");
    }
}
